from pydantic import BaseModel, Field
from uuid import UUID
from typing import Literal

class IngestionMetrics(BaseModel):
    original_paragraphs: int = Field(..., description="Number of paragraphs in the original document")
    removed_boilerplate: int = Field(..., description="Number of paragraphs removed as boilerplate")
    textrank_retained: int = Field(..., description="Number of paragraphs retained by TextRank algorithm")
    simhash_removed: int = Field(..., description="Number of paragraphs removed due to SimHash similarity")

class DocumentIngestRequest(BaseModel):
    filename: str = Field(..., description="The name of the uploaded file")
    raw_markdown: str = Field(..., description="The cleaned markdown text generated by the frontend pipeline")
    metrics: IngestionMetrics = Field(..., description="Metrics detailing text reduction process")
    tenant_id: str = Field(..., description="Identifier for data isolation")

class DocumentIngestResponse(BaseModel):
    document_id: UUID = Field(..., description="Generated UUID for the ingested document")
    status: Literal["processing", "completed"] = Field(..., description="Status of the document ingestion")
    language_detected: str = Field(..., description="Detected language of the document")
