from pydantic import BaseModel, Field
from uuid import UUID

class IngestionMetrics(BaseModel):
    original_paragraphs: int = Field(..., description="Number of paragraphs in the original document")
    removed_boilerplate: int = Field(..., description="Number of boilerplate paragraphs removed")
    textrank_retained: int = Field(..., description="Number of paragraphs retained by TextRank")
    simhash_removed: int = Field(..., description="Number of paragraphs removed by SimHash due to near-duplicate detection")

class DocumentIngestRequest(BaseModel):
    filename: str = Field(..., description="Name of the file being ingested")
    raw_markdown: str = Field(..., description="The cleaned markdown text generated by the frontend pipeline")
    metrics: IngestionMetrics = Field(..., description="Metrics from the CleanDocs pipeline")
    tenant_id: str = Field(..., description="Tenant ID for strict data isolation")

class DocumentIngestResponse(BaseModel):
    document_id: UUID = Field(..., description="Generated unique ID for the document")
    status: str = Field(..., description="Status of the ingestion process (e.g., 'processing' or 'completed')")
    language_detected: str = Field(..., description="Detected language of the document")
